### ISSUE TITLE
["StringLiteral"] but instead got "CallExpression"

### ISSUE THREAD

**Issue by wangfengyuan** [wuqiang1985/i18n-helper#7]
运行examples下面的两个例子，都报错误如下

` ~/i18n-helper/e/react-demo  master  npm run i18n                                                              

> react-demo@0.1.0 i18n /Users/i18n-helper/examples/react-demo
> i18n-helper scan -wetc

【开始】-【包裹】,【提取】,【翻译 - 从源文件翻译】,【统计】词条
本次需扫描文件【6】个
TypeError: /Users/i18n-helper/examples/react-demo/src/App.js: Property source of ImportDeclaration expected node to be of a type ["StringLiteral"] but instead got "CallExpression"
    at Object.validate (/Users/i18n-helper/examples/react-demo/node_modules/@babel/types/lib/definitions/utils.js:130:11)
    at validateField (/Users/i18n-helper/examples/react-demo/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at Object.validate (/Users/i18n-helper/examples/react-demo/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at NodePath._replaceWith (/Users/i18n-helper/examples/react-demo/node_modules/@babel/traverse/lib/path/replacement.js:147:7)
    at NodePath.replaceWith (/Users/i18n-helper/examples/react-demo/node_modules/@babel/traverse/lib/path/replacement.js:129:8)
    at PluginPass.StringLiteral (/Users/i18n-helper/examples/react-demo/node_modules/i18n-helper-cli/src/plugin/babelPlugin.js:67:30)
    at newFn (/Users/i18n-helper/examples/react-demo/node_modules/@babel/traverse/lib/visitors.js:171:21)
    at NodePath._call (/Users/i18n-helper/examples/react-demo/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/Users/i18n-helper/examples/react-demo/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/Users/i18n-helper/examples/react-demo/node_modules/@babel/traverse/lib/path/context.js:90:31) {
  code: 'BABEL_TRANSFORM_ERROR'
}`

**Comment by wuqiang1985** [comment]
我试了下直接clone一份代码到本地，运行demo
1. demo里的配置有几个字段缺失，导致i18n-helper init -y 报错，已fix，还未发布npm，预计下周发布，本周太忙
2. 当加上后我本地是ok的
3. react demo 运行npm run i18n 正常，当再运行npm start开启站点时会有一个babel-test的冲突，跟我后面加的单元测试有关，删掉根目录的node-module可以正常运行。应该是版本问题，具体我下周再看
